name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
    paths:
      - "public/**"
      - ".github/workflows/pages.yml"
  workflow_dispatch: {}
permissions:
  pages: write
  id-token: write
  contents: read
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - id: deployment
        uses: actions/deploy-pages@v4
