name: Scrape Filmweb ratings
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run scrape
      - name: Commit ratings.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add public/ratings.json
          git commit -m "update ratings.json" || echo "no changes"
          git push
